// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByPF04OCUKloe6VCtTit2L82jqua6_qxs',
    appId: '1:63188644980:web:914818419685d787a28d21',
    messagingSenderId: '63188644980',
    projectId: 'task-management-5101e',
    authDomain: 'task-management-5101e.firebaseapp.com',
    storageBucket: 'task-management-5101e.appspot.com',
    measurementId: 'G-7K8132JL05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg3bV6vgIBpNxCTyR9QOOx2ViHVL8_IBM',
    appId: '1:63188644980:android:0b859766421a496ea28d21',
    messagingSenderId: '63188644980',
    projectId: 'task-management-5101e',
    storageBucket: 'task-management-5101e.appspot.com',
  );

}